---
title: "pbsEDM vignettes"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{simple_time_series}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r start, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width = 6,
  fig.height = 6
)
options(rmarkdown.html_vignette.check_title = FALSE)
# rmarkdown::render("index.Rmd")
```

## Vignettes

The vignettes for our [pbsEDM R](https://github.com/pbs-assess/pbsEDM) package are already rendered here:

* [analyse_simple_time_series.html](https://pbs-assess.github.io/pbsEDM/vignettes/analyse_simple_time_series.html) How to analyse a simple time series using the simplex algorithm, and produce figures that help understand the algorithm.
* [aspect_2.html](https://pbs-assess.github.io/pbsEDM/vignettes/aspect_2.html) Detailing of aspect 2.
* [negative_predictions.html](https://pbs-assess.github.io/pbsEDM/vignettes/negative_predictions.html) Demonstrations of getting negative predictions, and also how the correlation coefficients differ between looking at predictions of lagged values and predictions of the actual population values.
* [pbsSmap.html](https://pbs-assess.github.io/pbsEDM/vignettes/pbsSmap.html) Demonstration of S-map code.

The source code written in `Rmarkdown`, the R code that gets extracted from the
`Rmarkdown` code, and the resulting .html files are all found within your library
folder (where all your R libraries get saved), in
`library\pbsEDM\doc\`. Or you can look at the
[vignettes](https://github.com/pbs-assess/pbsEDM/tree/main/vignettes/) folder on GitHub or locally. Terms like `aspect 2' will make more sense upon reading of the manuscript.
