---
title: "mve_understanding"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{mve}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width = 7.1,
  fig.height = 6,
  fig.retina = 2
)
```

```{r setup}
load_all() # library(pbsEDM)
library(dplyr)
library(tidyr)
library(magrittr)
library(ggplot2)
```

Adapting Luke's original `mve.Rmd` to dig into his mve functions. Also going to
use the same default time series as in `analyse_simple_time_series.Rmd` as used
for the first manuscript.

```{r visualize}
# Larkin
ggplot(data = larkin, aes(x = time, y = recruits)) +
  geom_line()

# Ricker
ggplot(data = ricker, aes(x = time, y = recruits)) +
  geom_line()

```

```{r forecast}
# Larkin
if(TRUE){
  f0 <- pbsEDM::single_view_embedding(
    data = larkin,
    response = "recruits",
    lags = list(spawners = 0:8),
    index = 60,
    buffer = 10,
    window = integer(0),
    metric = "rmse",
    beyond = FALSE
  )

  f0 %>% as.data.frame()
}

# Larkin
if(TRUE){
  f01 <- pbsEDM::mve(
    data = larkin,
    response = "recruits",
    lags = list(spawners = 0:8),
    index = 60,
    buffer = 10,
    window = integer(0),
    metric = "rmse",
    beyond = FALSE,
    weight = NULL,
    n_weight = 1,
    cores = NULL)

  f01$ranks
  f01$summary
  f01$hindsight
  f01$results
  f01$forecast
}
```
